import subprocess

"""
This module provides a utility function to create an array with random numbers.
The random numbers are generated by using the 'shuf' command via subprocess.
"""

def random_array(arr):
    """
    Populates the given array with random numbers using the 'shuf' command.
    
    Args:
        arr (list): List to populate with random numbers.
    
    Returns:
        list: List populated with random numbers.
    """
    shuf_command = "/usr/bin/shuf"  # Specify the full path to the shuf command
    for i, _ in enumerate(arr):
        shuffled_num = subprocess.run([shuf_command, "-i1-20", "-n1"], capture_output=True, check=True)
        arr[i] = int(shuffled_num.stdout)
    return arr